version: '3.8'

services:
  resume-tailor-api:
    build: .
    container_name: resume-tailor-ai
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-llama-3.3-70b-versatile}
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - resume-tailor-network

networks:
  resume-tailor-network:
    driver: bridge

